### PR TITLE
Make it faster for big forms

### PR DESCRIPTION
**Pull request by krizka**
This try-catch impacts hugely on performance for big forms. After profiling and removal, my input updates become faster about 3 times. But performance is still not very good due to full form re-rendering

### CODE REVIEW

**Comment by joepuzzo** [comment]
Hey thanks for pointing this out. I will verify that it all works in the AM and pull.

**Comment by krizka** [comment]
Thanks!

**Comment by tiffwu** [comment]
This update broke my form.

**Comment by krizka** [comment]
Please explain, what happened? Some code?

**Comment by tiffwu** [comment]
Sometimes `current` is null, which results in 
```
Uncaught TypeError: Cannot read property '0' of null```

**Comment by LyhjeHylje** [comment]
This happened to me also: 2.14.1 works but 2.14.2 throws intermittent "Cannot read property of null" errors.

**Comment by krizka** [comment]
@LyhjeHylje @tiffwu yeah, im really sorry, I led you to this. let we wait a bit for this to be fixed with @tiffwu PR.

**Pull request merged**
