### PR TITLE
Added inputRef prop

### PR DESCRIPTION
**Pull request by hosmelq**

### CODE REVIEW

**Comment by tannerlinsley** [comment]
What do you use this ref for?

**Comment by hosmelq** [comment]
For example add focus to an input programmatically.

**Comment by tannerlinsley** [comment]
Good point :)  Could you please add this to the rest of the input types?

**Comment by hosmelq** [comment]
Sure, when i have some time i'll update the PR :)

**Comment by 3bola** [comment]
Can we get this in?

**Comment by hhff** [comment]
I have a use-case for this too!

**Comment by warrenmcquinn** [comment]
Hey, wondering if this inputRef will be added to the Styled components at any point (maybe in 3.0)

**Comment by sanderfish** [comment]
Is there any way to use this?

**Pull request closed without merging**
